#babushka
#image: aws/codebuild/standard:5.0
#computeType: BUILD_GENERAL1_LARGE
#gitversionworkaround: true

version: 0.2

phases:
  pre_build:
    commands:
      - echo Build started on `date`
  install:
      runtime-versions:
        java: corretto11
  build:
    commands:
      - JFROG_BINTRAY_ACCESS_KEY=$(aws ssm get-parameter --name '/build/variables/JFROG_BINTRAY_ACCESS_KEY' --query Parameter.Value --output text)
      - ./gradlew bintrayUpload
  post_build:
    commands:
      - echo Build completed on `date`
